- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Copy index.html file  # Use 'template' for dynamic content
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Ensure Apache is running
  service:
    name: httpd
    state: started
    enabled: yes