---
- hosts: all
  become: true
  tasks:
    - name: Update package cache (Ubuntu)
      apt: 
        update_cache: yes
      when: ansible_distribution == 'Ubuntu'

    - name: Update package cache (CentOS)
      yum:
        name: '*'
        state: latest
      when: ansible_distribution == 'CentOS'


- hosts: nginx
  roles:
    - nginx

- hosts: webservers
  roles:
    - webserver